version: '3.9'

services:
  web:
    image: nginx:alpine
    container_name: my_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  
  app:
    build: 
      context: .
    container_name: app_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Tokyo
    command: uvicorn draft:app --host 0.0.0.0 --port 8000 --reload
  
  db:
    image: ankane/pgvector
    container_name: postgres_vector_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_vector_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: