services:
  web:
    image: nginx:alpine
    container_name: my_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build: 
      context: .
    container_name: app_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/draft
      - TZ=Asia/Tokyo
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: uvicorn draft:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build:
      context: .
    container_name: celery_worker
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/draft
      - TZ=Asia/Tokyo
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"

  db:
    image: ankane/pgvector
    container_name: postgres_vector_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_vector_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
